name: Docker Image CI

on:
  schedule:
    - cron: '5 4,8 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Trigger dockerhub
      run: curl -X POST https://hub.docker.com/api/build/v1/source/fb62723f-60c8-4dde-88df-8d154f690c0f/trigger/24afec77-6476-4383-b4fa-156a25f8c23d/call/
